[package]
name = "software-renderer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.0"
image = "0.24.6"
rand = "0.8.5"
raylib = "3.7.0"
tobj = "4.0.0"
